name: sync2gear
description: Sync2Gear mobile app
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  provider: ^6.1.2
  just_audio: ^0.9.36
  audio_session: ^0.1.21
  just_audio_background: any
  shared_preferences: ^2.3.2
  file_picker: ^10.3.10
  record: ^6.2.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"
